FROM --platform=$TARGETPLATFORM nvidia/cuda:12.1.1-devel-ubuntu22.04
LABEL maintainer="Chen Yijun"

ARG BUILD_DATE
ARG BUILD_VERSION

LABEL org.label-schema.build-date=$BUILD_DATE
LABEL org.label-schema.version=$BUILD_VERSION

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
        bash ca-certificates wget git gcc sudo curl libgl1 libglib2.0-0 \
        && rm -rf /var/lib/apt/lists/*

RUN echo "LD_PRELOAD=/usr/lib/libtcmalloc.so.4" | tee -a /etc/environment

RUN useradd --home /app -M app -K UID_MIN=10000 -K GID_MIN=10000 -s /bin/bash
RUN mkdir /app
RUN chown app:app -R /app
RUN usermod -aG sudo app
RUN echo 'app ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER app
WORKDIR /app/

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-$(uname -m).sh
RUN bash ./Miniconda3-latest-Linux-$(uname -m).sh -b \
    && rm -rf ./Miniconda3-latest-Linux-$(uname -m).sh

RUN git clone https://github.com/imClumsyPanda/langchain-ChatGLM.git /app/langchain-ChatGLM
WORKDIR /app/langchain-ChatGLM

ENV PATH /app/miniconda3/bin/:$PATH

RUN conda install python="3.10" -y

RUN python -m pip install --upgrade pip

RUN pip3 install -r requirements.txt && rm -rf `pip3 cache dir`

CMD ["python3","-u", "webui.py"]
