FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

WORKDIR /whisperapp

RUN apt-get -y update && apt-get install -y python3.9 \
ffmpeg \
python3-pip
RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install -U openai-whisper
RUN echo "All packages installed successfully"

#COPY . .

EXPOSE 7860

