FROM --platform=$TARGETPLATFORM nvidia/cuda:12.1.1-devel-ubuntu22.04
LABEL maintainer="Chen Yijun"

ARG BUILD_DATE
ARG BUILD_VERSION

LABEL org.label-schema.build-date=$BUILD_DATE
LABEL org.label-schema.version=$BUILD_VERSION

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
        bash ca-certificates wget git gcc sudo libgl1 libglib2.0-dev python3-dev google-perftools git-lfs \
        && rm -rf /var/lib/apt/lists/* && git lfs install

RUN echo "LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4" | tee -a /etc/environment

RUN useradd --home /app -M app -K UID_MIN=10000 -K GID_MIN=10000 -s /bin/bash
RUN mkdir /app
RUN chown app:app -R /app
RUN usermod -aG sudo app
RUN echo 'app ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER app
WORKDIR /app/

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-$(uname -m).sh
RUN bash ./Miniconda3-latest-Linux-$(uname -m).sh -b \
    && rm -rf ./Miniconda3-latest-Linux-$(uname -m).sh

ENV PATH /app/miniconda3/bin/:$PATH

RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git /app/stable-diffusion-webui

WORKDIR /app/stable-diffusion-webui

RUN mkdir ./openai && git clone https://huggingface.co/openai/clip-vit-large-patch14 ./openai/clip-vit-large-patch14 && rm -r ./openai/clip-vit-large-patch14/.git ./openai/clip-vit-large-patch14/flax_model.msgpack ./openai/clip-vit-large-patch14/pytorch_model.bin ./openai/clip-vit-large-patch14/tf_model.h5

RUN conda install python="3.10" -y

RUN touch install.log && \
    timeout 2h bash -c "./webui.sh --skip-torch-cuda-test --no-download-sd-model 2>&1 | tee install.log &" && \
    sleep 5 && while true; do grep -q "No checkpoints found." install.log && exit 0; grep -q "ERROR" install.log && exit 1; sleep 3; done

RUN venv/bin/pip install --force-reinstall --no-deps xformers==0.0.21

RUN rm -rf `pip3 cache dir`

CMD ["bash", "webui.sh", "--listen"]