name: Docker Image CI

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: setup versioning
      id: vars
      run: |
        build_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        build_version="$(date -u +'%Y-%m-%d')"
        echo "build_date=$build_date" >> $GITHUB_OUTPUT
        echo "build_version=$build_version" >> $GITHUB_OUTPUT
        
    - name: Build and push sdw
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.sdw
        build-args: |
          BUILD_DATE=${{ steps.vars.outputs.build_date }}
          BUILD_VERSION=${{ steps.vars.outputs.build_version }}
        push: true
        tags: |
          cyijun/lm_dockers:latest-sdw
          cyijun/lm_dockers:sdw-${{ steps.vars.outputs.build_version }}
        platforms: linux/amd64

    - name: Build and push lc
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.lc
        build-args: |
          BUILD_DATE=${{ steps.vars.outputs.build_date }}
          BUILD_VERSION=${{ steps.vars.outputs.build_version }}
        push: true
        tags: |
          cyijun/lm_dockers:latest-lc
          cyijun/lm_dockers:lc-${{ steps.vars.outputs.build_version }}
        platforms: linux/amd64
